name: Lint

on: [push]

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Analysing the code with pylint
        run: pylint $(git ls-files '*.py')
