name: "PR Title Checker"
on:
  pull_request_target:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        converted_to_draft,
        edited,
        labeled,
        unlabeled,
      ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4

  echo:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - run: echo "Hello World!"
